name: Build Python Executable

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code from the repository
      - name: Checkout Code
        uses: actions/checkout@v3

      # Step 2: Set up Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10" # Adjust the Python version if needed

      # Step 3: Install dependencies
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Step 4: Build the executable
      - name: Build Executable
        run: |
          pyinstaller --onefile your_script.py  # Add other PyInstaller options as needed

      # Step 5: Upload the built executable as an artifact
      - name: Upload Executable
        uses: actions/upload-artifact@v3
        with:
          name: python-executable
          path: dist/your_script # Replace with the correct path to the built executable
